"""Repository hygiene checks for this folder (public repository; see the README).

Two kinds of check, used by `test_rwm.py` and runnable as `python -m rwm.hygiene`:

* **Text hygiene.** Every file git would track here must be UTF-8 without hidden
  characters (controls other than tab, LF and CR; Unicode format characters such as
  zero-width, bidi and tag characters; private-use characters; line and paragraph
  separators) and without absolute local paths (drive letters, user-home folders), so no
  machine or user name reaches the repository and no invisible text changes how a file
  reads to a person or a model.
* **Standalone workspace.** This folder is its own Cargo workspace. An enclosing
  workspace (a future root `Cargo.toml`) must `exclude` it and must not name a crate in it
  as a member, and no toolchain pin or cargo config may sit between it and the repository
  root, because each would silently change how the experiment compiles.

Standard library only; `tomllib` (Python 3.11+) is needed for the workspace check.
"""
from __future__ import annotations

import os
import re
import sys
import unicodedata
from pathlib import Path, PurePosixPath

try:
    import tomllib
except ModuleNotFoundError:  # Python < 3.11: the workspace check is skipped by its tests
    tomllib = None

from .tasks import ROOT

# ── What git would track here (mirrors .gitignore) ─────────────────────────────

# Top-level folders with build or run output, and caches anywhere.
_SKIP_TOP = {"target", "results"}
_SKIP_ANY = {"__pycache__", ".pytest_cache"}
# Generated by `python runner.py scaffold`: <tasks|pilot>/<id>/<plain|guided>/.
_GENERATED_PARENTS = {"tasks", "pilot"}
_GENERATED_NAMES = {"plain", "guided"}
_SKIP_FILES = {"Cargo.lock", "live/arms.local.json"}


def candidate_files(root: Path = ROOT) -> list[Path]:
    """Files under `root` that .gitignore does not exclude, sorted by path."""
    out = []
    for dirpath, dirnames, filenames in os.walk(root):
        rel_dir = Path(dirpath).relative_to(root)
        parts = rel_dir.parts
        keep = []
        for d in dirnames:
            if d in _SKIP_ANY or (not parts and d in _SKIP_TOP):
                continue
            if len(parts) == 2 and parts[0] in _GENERATED_PARENTS and d in _GENERATED_NAMES:
                continue
            keep.append(d)
        dirnames[:] = keep  # prune in place so os.walk never descends into skipped folders
        for f in filenames:
            rel = (rel_dir / f).as_posix()
            if rel not in _SKIP_FILES:
                out.append(Path(dirpath) / f)
    return sorted(out)


# ── Text hygiene ──────────────────────────────────────────────────────────────

# Unicode categories that are invisible or change rendering: Cc controls (tab, LF and CR
# are allowed separately), Cf format characters (zero-width, bidi, BOM, soft hyphen, tag
# characters), Co private use, Zl/Zp line and paragraph separators.
_HIDDEN_CATEGORIES = {"Cc", "Cf", "Co", "Zl", "Zp"}
_ALLOWED_CONTROLS = {chr(0x09), chr(0x0A), chr(0x0D)}  # tab, LF, CR
# Characters other than LF and CR at which str.splitlines() also breaks a line (vertical
# tab, form feed, file/group/record separators, NEL, line and paragraph separators).
# Written as code points so this source file holds no such character itself.
_LINE_SPLITTERS = {chr(c) for c in (0x0B, 0x0C, 0x1C, 0x1D, 0x1E, 0x85, 0x2028, 0x2029)}

# Absolute local paths. The patterns are written so that this file does not match itself:
# a drive letter must be followed directly by ":" and a slash; user-home folders must start
# a path; the per-user application-data folder name is split by a character class.
_LOCAL_PATHS = [
    (re.compile(r"(?<![A-Za-z0-9_])[A-Za-z]:[\\/]"), "drive-letter path"),
    (re.compile(r"(?i)(?:^|[\s\"'`(=])[\\/](?:users|home)[\\/]"), "user-home path"),
    (re.compile(r"(?i)app[d]ata"), "per-user application-data folder"),
]


def text_problems(text: str) -> list[str]:
    """Hidden characters and local paths in `text`, one message per finding, each with
    its line number (and the code point for a hidden character)."""
    problems = []
    for n, line in enumerate(text.splitlines(keepends=False) or [text], 1):
        for ch in line:
            if ch in _ALLOWED_CONTROLS:
                continue
            cat = unicodedata.category(ch)
            if cat in _HIDDEN_CATEGORIES:
                name = unicodedata.name(ch, "unnamed")
                problems.append(f"line {n}: hidden character U+{ord(ch):04X} {name} ({cat})")
        for pattern, what in _LOCAL_PATHS:
            if pattern.search(line):
                problems.append(f"line {n}: {what}")
    # str.splitlines() also splits on U+2028/U+2029 and a few controls, which would hide
    # them from the per-line scan above; report them from the whole text instead.
    for ch in sorted({c for c in text if c in _LINE_SPLITTERS}):
        cat = unicodedata.category(ch)
        problems.append(f"hidden character U+{ord(ch):04X} {unicodedata.name(ch, 'unnamed')} ({cat})")
    return problems


def scan_tree(root: Path = ROOT) -> list[str]:
    """Text-hygiene findings for every candidate file, as `path: message`."""
    problems = []
    for path in candidate_files(root):
        rel = path.relative_to(root).as_posix()
        try:
            text = path.read_bytes().decode("utf-8")
        except UnicodeDecodeError as e:
            problems.append(f"{rel}: not UTF-8 ({e.reason} at byte {e.start})")
            continue
        problems.extend(f"{rel}: {p}" for p in text_problems(text))
    return problems


# ── Standalone workspace ──────────────────────────────────────────────────────


def repo_root(start: Path = ROOT) -> Path | None:
    """The nearest folder at or above `start` that holds `.git` (a folder, or a file in a
    worktree); None outside a git checkout."""
    for d in [start, *start.parents]:
        if (d / ".git").exists():
            return d
    return None


def _between(harness: Path, top: Path) -> list[Path]:
    """Folders strictly above `harness`, up to and including `top`."""
    out = []
    for d in harness.parents:
        out.append(d)
        if d == top:
            break
    return out


def _is_within(rel: PurePosixPath, base: str) -> bool:
    b = PurePosixPath(base.strip().rstrip("/").removeprefix("./"))
    return rel == b or b in rel.parents


def enclosing_workspace_problems(harness: Path, top: Path) -> list[str]:
    """Every Cargo workspace above `harness` (up to `top`) that could adopt its crates.

    A root workspace must list the harness folder (or a parent of it) in `exclude`, and
    must not name a path inside it in `members`: cargo lets an explicit member path win
    over `exclude`, and adopts such a crate without an error."""
    problems = []
    for d in _between(harness, top):
        manifest = d / "Cargo.toml"
        if not manifest.is_file():
            continue
        data = tomllib.loads(manifest.read_text(encoding="utf-8"))
        ws = data.get("workspace")
        if ws is None:
            continue  # a package without [workspace] never adopts other packages
        rel = PurePosixPath(harness.relative_to(d).as_posix())
        where = manifest.relative_to(top).as_posix()
        if not any(_is_within(rel, e) for e in ws.get("exclude", [])):
            problems.append(f'{where} declares a workspace but does not exclude this harness: add '
                            f'exclude = ["{rel}"] to its [workspace] table')
        for m in ws.get("members", []):
            if not any(c in m for c in "*?[") and _is_within(PurePosixPath(m.strip().removeprefix("./")), str(rel)):
                problems.append(f'{where} names "{m}" as a member; cargo adopts it even when excluded: '
                                f"remove it (this harness is its own workspace)")
    return problems


# Files that change how cargo or rustup build everything below them.
_CONFIG_FILES = ("rust-toolchain", "rust-toolchain.toml", ".cargo/config", ".cargo/config.toml")


def enclosing_config_problems(harness: Path, top: Path) -> list[str]:
    """Toolchain pins and cargo configs above `harness` (up to `top`). The harness pins no
    toolchain on purpose (a pin can trigger a rustup download, which an offline run must
    never do) and records `rustc --version` per run; an enclosing pin or config would
    change the compiler or flags without showing up in that record."""
    problems = []
    for d in _between(harness, top):
        for name in _CONFIG_FILES:
            if (d / name).is_file():
                problems.append(f"{(d / name).relative_to(top).as_posix()} applies to this harness too: decide whether the "
                                "experiment should use it, then pin the choice in this folder and record it in the README")
    return problems


def main() -> int:
    files = candidate_files(ROOT)
    total = sum(p.stat().st_size for p in files)
    problems = scan_tree(ROOT)
    top = repo_root(ROOT)
    if top is not None and tomllib is not None:
        problems += enclosing_workspace_problems(ROOT, top) + enclosing_config_problems(ROOT, top)
    print(f"{len(files)} files, {total} bytes scanned; {len(problems)} problem(s)")
    for p in problems:
        print(f"  {p}")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
